# Appveyor configuration
#

environment:
  GENERATOR: "MinGW Makefiles"
  ARTIFACT_BRANCH: debug-midi
  matrix:

    - job_name: 'Ubuntu 20.04'
      job_group: 'Linux'
      appveyor_build_worker_image: Ubuntu2004

    - job_name: 'OS X'
      job_group: 'Mac OS X'
      appveyor_build_worker_image: macos

    - job_name: 'Windows64'
      job_group: 'Windows'
      MSYS: 'C:\msys64\mingw64'
      MSYS_REPO: 'mingw64/mingw-w64-x86_64'
      BUILD_TYPE: "Release"
      CMAKE_FLAGS: "-DWANT_DEBUG:BOOL=OFF -DWIN64:BOOL=ON"
      appveyor_build_worker_image: Visual Studio 2019
      LIBJACK: libjack64.dll
      OPENSSL_DIR: OpenSSL-Win64
      LIBSSL: libssl-1_1-x64.dll
      LIBCRYPTO: libcrypto-1_1-x64.dll

      CHOCO_ARCH:
      PROGRAM_FILES: "Program Files"

    - job_name: 'Windows32'
      job_group: 'Windows'
      MSYS: 'C:\msys64\mingw32'
      MSYS_REPO: 'mingw-w64-i686'
      BUILD_TYPE: "Release"
      CMAKE_FLAGS: "-DWANT_DEBUG:BOOL=OFF -DWIN64:BOOL=OFF"
      appveyor_build_worker_image: Visual Studio 2019
      LIBJACK: libjack.dll
      OPENSSL_DIR: OpenSSL-Win32
      LIBSSL: libssl-1_1.dll
      LIBCRYPTO: libcrypto-1_1.dll

      CHOCO_ARCH:  --x86
      PROGRAM_FILES: "Program Files (x86)"

build:
  verbosity: detailed

matrix:
  exclude:
    - job_name: Windows32
      branches: "master"

for:
  - 
    matrix:
      only:
        - job_group: 'Linux'

    cache: $HOME/cache_dir


    build_script: |-
      rm -rf $HOME/cache_dir
      true


  - 
    cache: /Users/appveyor/cache_dir
    matrix:
      only:
        - job_group: 'Mac OS X'

    build_script: |-
      rm -rf /Users/appveyor/cache_dir

  -
    matrix:
      only:
        - job_group: 'Windows'

    cache: '%USERPROFILE%\AppData\Roaming\ccache'

build_script:
      - cmd: |-
          deltree %USERPROFILE%\AppData\Roaming\ccache
